name = "backend"
compatibility_date = "2024-07-23"

[vars]
POOLING_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTc5NTA2YzAtZTFkNS00NTQ0LWE2ZjAtZWUwZGJhNDIwMTU3IiwidGVuYW50X2lkIjoiMTY4NjI0NjIwOTlkNDU4MTEyZWUxZTBmZTA5MTZiMjA3NWM5MjIwNjMyODQ5NDkwN2NhYmY0ZTFmNzVjNGZiMyIsImludGVybmFsX3NlY3JldCI6IjkwMmYyNTg3LTI3ODktNGUwMy04YmE5LTlmZTUxYmM4MWRmZCJ9.Pe4dnDn_XvYmjvBonMq4MtDo05t1ilUTvhZ5TO0V9ls"
JWT_SECRET="Kiara-is-hot"
